# Generated by Django 4.1.5 on 2023-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
