# Generated by Django 4.1.7 on 2023-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profession_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
