# Generated by Django 4.1.5 on 2023-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_profession_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='profession_no',
            field=models.IntegerField(null=True),
        ),
    ]
