# Generated by Django 4.1.5 on 2023-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_profession_profession_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='roll',
            new_name='roll_profrssion',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='profession_no',
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_no',
            field=models.ManyToManyField(blank=True, null=True, to='members.student'),
        ),
    ]
